### ISSUE TITLE
Typo in ElectricCharge resourcename

### ISSUE THREAD

**Issue by JonnyOThan** [A-T-L-A-S/XenonGas-ISRU#1]
https://github.com/A-T-L-A-S/XenonGas-ISRU/blob/f9113bae4e8b156c519105b2ff60246e2f6473c8/ISRU.cfg#L22

https://github.com/A-T-L-A-S/XenonGas-ISRU/blob/f9113bae4e8b156c519105b2ff60246e2f6473c8/miniISRU.cfg#L22

**Comment by A-T-L-A-S** [comment]
Thanks. I hate coding for typos like this haha!
Fixed it.
